import { Registry } from "@/registry/schema"

export const examples: Registry = [
  {
    name: "badge-group-demo",
    type: "registry:example",
    registryDependencies: ["badge-group"],
    files: ["example/badge-group-demo.tsx"],
  },
  {
    name: "badge-group-form",
    type: "registry:example",
    registryDependencies: ["badge-group", "button", "form"],
    files: ["example/badge-group-form.tsx"],
  },
  {
    name: "calendar-demo",
    type: "registry:example",
    registryDependencies: ["calendar"],
    files: ["example/calendar-demo.tsx"],
  },
  {
    name: "calendar-multiple",
    type: "registry:example",
    registryDependencies: ["calendar"],
    files: ["example/calendar-multiple.tsx"],
  },
  {
    name: "calendar-dropdown-layout",
    type: "registry:example",
    registryDependencies: ["calendar"],
    files: ["example/calendar-dropdown-layout.tsx"],
  },
  {
    name: "calendar-form",
    type: "registry:example",
    registryDependencies: ["calendar", "button", "form"],
    files: ["example/calendar-form.tsx"],
  },
  {
    name: "combobox-primitive-demo",
    type: "registry:example",
    registryDependencies: ["combobox-primitive"],
    files: ["example/combobox-primitive-demo.tsx"],
  },
  {
    name: "combobox-primitive-multi-select",
    type: "registry:example",
    registryDependencies: ["combobox-primitive"],
    files: ["example/combobox-primitive-multi-select.tsx"],
  },
  {
    name: "combobox-primitive-multiple",
    type: "registry:example",
    registryDependencies: ["combobox-primitive"],
    files: ["example/combobox-primitive-multiple.tsx"],
  },
  {
    name: "combobox-demo",
    type: "registry:example",
    registryDependencies: ["combobox"],
    files: ["example/combobox-demo.tsx"],
  },
  {
    name: "combobox-loading",
    type: "registry:example",
    registryDependencies: ["combobox"],
    files: ["example/combobox-loading.tsx"],
  },
  {
    name: "combobox-form",
    type: "registry:example",
    registryDependencies: ["button", "combobox", "form"],
    files: ["example/combobox-form.tsx"],
  },
  {
    name: "confirmer-demo",
    type: "registry:example",
    registryDependencies: ["confirmer", "toast"],
    files: ["example/confirmer-demo.tsx"],
  },
  {
    name: "confirmer-safe",
    type: "registry:example",
    registryDependencies: ["confirmer", "toast"],
    files: ["example/confirmer-safe.tsx"],
  },
  {
    name: "control-group-action",
    type: "registry:example",
    registryDependencies: [
      "button",
      "control-group",
      "input-base",
      "native-select",
    ],
    files: ["example/control-group-action.tsx"],
  },
  {
    name: "control-group-demo",
    type: "registry:example",
    registryDependencies: ["control-group", "input-base"],
    files: ["example/control-group-demo.tsx"],
  },
  {
    name: "control-group-form",
    type: "registry:example",
    registryDependencies: ["button", "control-group", "form", "input-base"],
    files: ["example/control-group-form.tsx"],
  },
  {
    name: "control-group-select",
    type: "registry:example",
    registryDependencies: ["control-group", "input-base", "select"],
    files: ["example/control-group-select.tsx"],
  },
  {
    name: "control-group-split-button",
    type: "registry:example",
    registryDependencies: ["button", "control-group", "dropdown-menu"],
    files: ["example/control-group-split-button.tsx"],
  },
  {
    name: "control-group-vertical",
    type: "registry:example",
    registryDependencies: ["control-group", "input-base"],
    files: ["example/control-group-vertical.tsx"],
  },
  {
    name: "date-field-demo",
    type: "registry:example",
    registryDependencies: ["date-field"],
    files: ["example/date-field-demo.tsx"],
  },
  {
    name: "date-field-form",
    type: "registry:example",
    registryDependencies: ["button", "date-field", "form"],
    files: ["example/date-field-form.tsx"],
  },
  {
    name: "date-time-field-primitive-demo",
    type: "registry:example",
    registryDependencies: ["date-time-field-primitive"],
    files: ["example/date-time-field-primitive-demo.tsx"],
  },
  {
    name: "date-time-field-primitive-disabled",
    type: "registry:example",
    registryDependencies: ["date-time-field-primitive"],
    files: ["example/date-time-field-primitive-disabled.tsx"],
  },
  {
    name: "date-time-field-demo",
    type: "registry:example",
    registryDependencies: ["date-time-field"],
    files: ["example/date-time-field-demo.tsx"],
  },
  {
    name: "date-time-field-form",
    type: "registry:example",
    registryDependencies: ["button", "date-time-field", "form"],
    files: ["example/date-time-field-form.tsx"],
  },
  {
    name: "date-time-range-field-primitive-demo",
    type: "registry:example",
    registryDependencies: ["date-time-range-field-primitive"],
    files: ["example/date-time-range-field-primitive-demo.tsx"],
  },
  {
    name: "date-time-range-field-primitive-disabled",
    type: "registry:example",
    registryDependencies: ["date-time-range-field-primitive"],
    files: ["example/date-time-range-field-primitive-disabled.tsx"],
  },
  {
    name: "date-time-range-field-demo",
    type: "registry:example",
    registryDependencies: ["date-time-range-field"],
    files: ["example/date-time-range-field-demo.tsx"],
  },
  {
    name: "date-time-range-field-form",
    type: "registry:example",
    registryDependencies: ["button", "date-time-range-field", "form"],
    files: ["example/date-time-range-field-form.tsx"],
  },
  {
    name: "date-picker-primitive-demo",
    type: "registry:example",
    registryDependencies: ["date-picker-primitive"],
    files: ["example/date-picker-primitive-demo.tsx"],
  },
  {
    name: "date-picker-primitive-input",
    type: "registry:example",
    registryDependencies: ["date-picker-primitive"],
    files: ["example/date-picker-primitive-input.tsx"],
  },
  {
    name: "date-picker-primitive-multiple",
    type: "registry:example",
    dependencies: ["date-fns"],
    registryDependencies: ["date-picker-primitive"],
    files: ["example/date-picker-primitive-multiple.tsx"],
  },
  {
    name: "date-picker-primitive-range",
    type: "registry:example",
    dependencies: ["date-fns", "react-day-picker"],
    registryDependencies: ["date-picker-primitive"],
    files: ["example/date-picker-primitive-range.tsx"],
  },
  {
    name: "date-picker-demo",
    type: "registry:example",
    registryDependencies: ["date-picker"],
    files: ["example/date-picker-demo.tsx"],
  },
  {
    name: "date-picker-input",
    type: "registry:example",
    registryDependencies: ["date-picker"],
    files: ["example/date-picker-input.tsx"],
  },
  {
    name: "date-picker-form",
    type: "registry:example",
    registryDependencies: ["button", "date-picker", "form"],
    files: ["example/date-picker-form.tsx"],
    dependencies: ["date-fns"],
  },
  {
    name: "description-list-demo",
    type: "registry:example",
    registryDependencies: ["description-list"],
    files: ["example/description-list-demo.tsx"],
  },
  {
    name: "dropzone-demo",
    type: "registry:example",
    registryDependencies: ["dropzone", "file-list"],
    files: ["example/dropzone-demo.tsx"],
  },
  {
    name: "dropzone-trigger",
    type: "registry:example",
    registryDependencies: ["button", "dropzone"],
    files: ["example/dropzone-trigger.tsx"],
  },
  {
    name: "dropzone-form",
    type: "registry:example",
    registryDependencies: [
      "button",
      "dropzone",
      "file-list",
      "form",
      "input-base",
    ],
    dependencies: ["pretty-bytes"],
    files: ["example/dropzone-form.tsx"],
  },
  {
    name: "file-list-demo",
    type: "registry:example",
    registryDependencies: ["file-list"],
    files: ["example/file-list-demo.tsx"],
  },
  {
    name: "input-base-demo",
    type: "registry:example",
    registryDependencies: ["input-base"],
    files: ["example/input-base-demo.tsx"],
  },
  {
    name: "input-base-with-action",
    type: "registry:example",
    registryDependencies: ["input-base", "tooltip"],
    files: ["example/input-base-with-action.tsx"],
  },
  {
    name: "input-base-disabled",
    type: "registry:example",
    registryDependencies: ["input-base"],
    files: ["example/input-base-disabled.tsx"],
  },
  {
    name: "input-base-form",
    type: "registry:example",
    registryDependencies: ["button", "form", "input-base"],
    files: ["example/input-base-form.tsx"],
  },
  {
    name: "kbd-demo",
    type: "registry:example",
    registryDependencies: ["kbd"],
    files: ["example/kbd-demo.tsx"],
  },
  {
    name: "kbd-outline",
    type: "registry:example",
    registryDependencies: ["kbd"],
    files: ["example/kbd-outline.tsx"],
  },
  {
    name: "kbd-secondary",
    type: "registry:example",
    registryDependencies: ["kbd"],
    files: ["example/kbd-secondary.tsx"],
  },
  {
    name: "native-select-demo",
    type: "registry:example",
    registryDependencies: ["native-select"],
    files: ["example/native-select-demo.tsx"],
  },
  {
    name: "native-select-form",
    type: "registry:example",
    registryDependencies: ["button", "form", "native-select"],
    files: ["example/native-select-form.tsx"],
  },
  {
    name: "sortable-demo",
    type: "registry:example",
    registryDependencies: ["sortable"],
    files: ["example/sortable-demo.tsx"],
  },
  {
    name: "sortable-disabled",
    type: "registry:example",
    registryDependencies: ["sortable"],
    files: ["example/sortable-disabled.tsx"],
  },
  {
    name: "sortable-form",
    type: "registry:example",
    registryDependencies: [
      "button",
      "dialog",
      "form",
      "input",
      "sortable",
      "textarea",
    ],
    files: ["example/sortable-form.tsx"],
  },
  {
    name: "sortable-swap",
    type: "registry:example",
    registryDependencies: ["sortable"],
    files: ["example/sortable-swap.tsx"],
  },
  {
    name: "sortable-trigger",
    type: "registry:example",
    registryDependencies: ["sortable"],
    files: ["example/sortable-trigger.tsx"],
  },
  {
    name: "time-field-demo",
    type: "registry:example",
    registryDependencies: ["time-field"],
    files: ["example/time-field-demo.tsx"],
  },
  {
    name: "time-field-hour-12",
    type: "registry:example",
    registryDependencies: ["time-field"],
    files: ["example/time-field-hour-12.tsx"],
  },
  {
    name: "time-field-form",
    type: "registry:example",
    registryDependencies: ["button", "time-field", "form"],
    files: ["example/time-field-form.tsx"],
  },
  {
    name: "time-demo",
    type: "registry:example",
    registryDependencies: ["time"],
    files: ["example/time-demo.tsx"],
  },
  {
    name: "time-format",
    type: "registry:example",
    registryDependencies: ["time"],
    files: ["example/time-format.tsx"],
  },
  {
    name: "timeline-demo",
    type: "registry:example",
    registryDependencies: ["timeline"],
    files: ["example/timeline-demo.tsx"],
  },
  {
    name: "timeline-alternate",
    type: "registry:example",
    registryDependencies: ["timeline"],
    files: ["example/timeline-alternate.tsx"],
  },
  {
    name: "timeline-with-icon",
    type: "registry:example",
    registryDependencies: ["timeline"],
    files: ["example/timeline-with-icon.tsx"],
  },
  {
    name: "timeline-horizontal",
    type: "registry:example",
    registryDependencies: ["timeline"],
    files: ["example/timeline-horizontal.tsx"],
  },
  {
    name: "password-input-primitive-demo",
    type: "registry:example",
    registryDependencies: ["password-input-primitive"],
    files: ["example/password-input-primitive-demo.tsx"],
  },
  {
    name: "password-input-primitive-checkbox",
    type: "registry:example",
    registryDependencies: ["password-input-primitive"],
    files: ["example/password-input-primitive-checkbox.tsx"],
  },
  {
    name: "password-input-demo",
    type: "registry:example",
    registryDependencies: ["password-input"],
    files: ["example/password-input-demo.tsx"],
  },
  {
    name: "password-input-checkbox",
    type: "registry:example",
    registryDependencies: ["checkbox", "password-input"],
    files: ["example/password-input-checkbox.tsx"],
  },
  {
    name: "password-input-form",
    type: "registry:example",
    registryDependencies: ["button", "form", "password-input"],
    files: ["example/password-input-form.tsx"],
  },
  {
    name: "select-demo",
    type: "registry:example",
    registryDependencies: ["select"],
    files: ["example/select-demo.tsx"],
  },
  {
    name: "select-scrollable",
    type: "registry:example",
    registryDependencies: ["select"],
    files: ["example/select-scrollable.tsx"],
  },
  {
    name: "select-form",
    type: "registry:example",
    registryDependencies: ["select"],
    files: ["example/select-form.tsx"],
  },
]
